### ISSUE TITLE
Still can't install the root CA

### ISSUE THREAD

**Issue by pyretta** [MegatronKing/HttpCanary#118]
This is no new issue, but I don't know, how to reopen an closed issue, which is not fixed yet.
I have opened the following issue: https://github.com/MegatronKing/HttpCanary/issues/102
It was closed in April with the information that it was solved. But it's not.

Please, reopen it, it seems to be a bug of this app.
Thank you very much for your advice. I hope, we find a solution for this. Because your App seems to be exactly what I need. And if it works, I would buy the pro version.

**Comment by pyretta** [comment]
Is there a chance to solve this issue? Did you looked at it? Can you say what's the reason, why I still can't install the root certificate? Is there something I could do, to help you solving this issue?

Please help us to get this work. 
Thank you very much in advance.

**Comment by maxkatz6** [comment]
I can confirm same bug with android x86 7.1-r4 inside of Hyper-V emulator.

**Comment by pyretta** [comment]
Thanks @maxkatz6, to confirm I'm not the only one who has this Bug with an VM.

Please, @MegatronKing look at this issue. If we can help to solve it, let us know. 
Thank you very much.

**Comment by Londek** [comment]
Same issue
Nox player on Android 7

**Comment by D-4-N** [comment]
@MegatronKing I am experiencing the same issue.

System: Android 7.1 x86_64 (Rooted) VM 
Version: HttpCanary 3.3.5 (Free)

Judging from your [comment](https://github.com/MegatronKing/HttpCanary/issues/102#issuecomment-607311009) on @pyretta 's issue #102, and judging from the following logcat data, I suspect it has something to do with the way HttpCanary implements [this](https://github.com/MegatronKing/NetBare/blob/df5b417ea663763932cabf1ef52f15b09ddc2e16/netbare-core/src/main/java/com/github/megatronking/netbare/ssl/CertificateInstallActivity.java#L42) method call
```
06-21 08:36:32.350   567  1102 I ActivityManager: START u0 {act=android.credentials.INSTALL cmp=com.android.certinstaller/.CertInstallerMain (has extras)} from uid 10062 on display 0
06-21 08:36:32.381  3003  3003 D CredentialHelper: # extras: 3
06-21 08:36:32.381  3003  3003 W Bundle  : Key android:viewHierarchyState expected byte[] but value was a android.os.Bundle.  The default value <null> was returned.
06-21 08:36:32.381  3003  3003 W Bundle  : Attempt to cast generated internal exception:
06-21 08:36:32.381  3003  3003 W Bundle  : java.lang.ClassCastException: android.os.Bundle cannot be cast to byte[]
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.BaseBundle.getByteArray(BaseBundle.java:1185)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Bundle.getByteArray(Bundle.java:1014)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CredentialHelper.<init>(CredentialHelper.java:97)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CertInstaller.createCredentialHelper(CertInstaller.java:86)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CertInstaller.onCreate(CertInstaller.java:98)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.Activity.performCreate(Activity.java:6682)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4520)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.-wrap19(ActivityThread.java)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Looper.loop(Looper.java:154)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:6121)
06-21 08:36:32.381  3003  3003 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 08:36:32.381  3003  3003 D CredentialHelper:    android:viewHierarchyState: -1
06-21 08:36:32.381  3003  3003 D CredentialHelper:    CERT: 1257
06-21 08:36:32.381  3003  3003 W Bundle  : Key alias expected byte[] but value was a java.lang.String.  The default value <null> was returned.
06-21 08:36:32.381  3003  3003 W Bundle  : Attempt to cast generated internal exception:
06-21 08:36:32.381  3003  3003 W Bundle  : java.lang.ClassCastException: java.lang.String cannot be cast to byte[]
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.BaseBundle.getByteArray(BaseBundle.java:1185)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Bundle.getByteArray(Bundle.java:1014)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CredentialHelper.<init>(CredentialHelper.java:97)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CertInstaller.createCredentialHelper(CertInstaller.java:86)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.certinstaller.CertInstaller.onCreate(CertInstaller.java:98)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.Activity.performCreate(Activity.java:6682)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4520)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.-wrap19(ActivityThread.java)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.os.Looper.loop(Looper.java:154)
06-21 08:36:32.381  3003  3003 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:6121)
06-21 08:36:32.381  3003  3003 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 08:36:32.381  3003  3003 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Could you please look into this?

**Comment by MegatronKing** [comment]
@D-4-N The log is a warning message, I don't think it is the cause. I will optimize the code in the next version, but I am not sure this works.

**Comment by Londek** [comment]
> @D-4-N The log is a warning message, I don't think it is the cause. I will optimize the code in the next version, but I am not sure this works.

Just install nox and test app here, you gonna get same results as we

**Comment by D-4-N** [comment]
Any updates on this @MegatronKing ?

**Comment by D-4-N** [comment]
@MegatronKing pinging you again since more than 15 days have passed since the last response

**Comment by pyretta** [comment]
@MegatronKing ... in the meantime I bought the pro version of your app and use it on a Samsung Galaxy S5. Probably the only way to use your app. But this phone has an old OS version - Android 6.0.1 and soon many apps will not be installable on it. 

I and as it seems many other users here really need your advice to get your app running on any platform (emulator and physical device) with the latest Android OS. Please take a look at this problem and help us to solve it. 

You say in your app description: "Support Devices: Any android arm or x86 devices include emulators". 
So please help us to keep your promise.

**Comment by pyretta** [comment]
@MegatronKing seems not to be willing to answer here, last reaction of him was on 22 June. What is not good costumer service, especially if someone bought his app, like me.

@maxkatz6, @D-4-N, @Londek: Did you find a sollution by yourself at the meantime? Did you find another app like this, which you can use instead? Unfortunately I did not.

**Comment by Wychell** [comment]
Estou com mesmo problema apresentado, porem estou usando o memu play.

com um celular fisico exporte o certificado  e improtei no emunado como as imagens.
![image](https://user-images.githubusercontent.com/15784111/93412633-e54a4a00-f873-11ea-8c32-3a33580218b0.png)

![image](https://user-images.githubusercontent.com/15784111/93412690-0743cc80-f874-11ea-9cbc-5373585f1e4f.png)
![image](https://user-images.githubusercontent.com/15784111/93412755-2c383f80-f874-11ea-9776-d5d46579d61d.png)


Porem ao abrir o aplicativo ele nao reconhece o certificado importado. 
![image](https://user-images.githubusercontent.com/15784111/93412725-1aef3300-f874-11ea-80af-ff97b00038a7.png)

![image](https://user-images.githubusercontent.com/15784111/93412783-3c501f00-f874-11ea-9ed0-15b82d3c66bd.png)
