### ISSUE TITLE
無法開啟最新版的 app

### ISSUE THREAD

**Issue by maple3142** [MegatronKing/HttpCanary#56]
如題，版本為 3.1.0，在 Google Play 上更新的
logcat 中有這個 error，可能有些幫助
```
Unable to instantiate appComponentFactory
java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/com.guoshi.httpcanary.premium-p2OfBoeu1xVxR_zLS43u5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.guoshi.httpcanary.premium-p2OfBoeu1xVxR_zLS43u5g==/lib/arm64, /data/app/com.guoshi.httpcanary.premium-p2OfBoeu1xVxR_zLS43u5g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
	at com.elderdrivers.riru.edxp._hooker.impl.HandleBindApp.beforeHookedMethod(HandleBindApp.java:67)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:19)
	at android.app.ActivityThread.access$1100(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MegatronKing** [comment]
3.1加了防hook的逻辑，禁用掉xposed等hook框架即可

**Comment by maple3142** [comment]
為何要禁止hook？這讓一些日常使用xposed的使用者很困擾

**Comment by MegatronKing** [comment]
非常抱歉，因为HttpCanary收到大量的Hook攻击以及逆向。不过，我已计划更新一个版本，尽快修复这个问题。

**Comment by MegatronKing** [comment]
Fixed, please update v3.1.2.
